### ISSUE TITLE
List of included boards?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [wilcotomassen/smd-protopack#1]
This looks neat, but I'm a newbie, and it'd be cool to see what all I'm gonna get ten copies of if I order a protopack of this!

**Comment by wilcotomassen** [comment]
You are right, I'll update it with a list and possibly some pictures of the boards.

**Comment by wilcotomassen** [comment]
Hey Elliott,

Updated the readme with hopefully some useful info.

Thanks!
